services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: icaro_password
      MYSQL_DATABASE: gac_database
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

  wallet-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      TYPEORM_HOST: mysql
      TYPEORM_PORT: 3306
      TYPEORM_USERNAME: icaro
      TYPEORM_PASSWORD: icaro_password
      TYPEORM_DATABASE: gac_database
      TYPEORM_SYNCHRONIZE: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M

  mysql-exporter:
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: "icaro:icaro_password@(mysql:3306)/gac_database"
    ports:
      - "9104:9104"
    deploy:
      replicas: 0 
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M

  filebeat:
    build:
      context: ./filebeat
    volumes:
      - /var/log:/var/log
      - filebeat-logs:/var/log/filebeat
    ports:
      - "5066:5066"
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M

volumes:
  mysql_data:
  filebeat-logs:
